Final Pull Request
mistermaxis/SpaceX pull request #33
Opened 2021-11-25 00:58 UTC by mistermaxis

### Tasks Completed:
- Create basic structure for Missions - Setup
- Fetch missions  - Fetch data
- Fetch rockets - Fetch data
- Display missions - List render
- Display rockets - List render
- Implement rocket booking - Actions
- Implement mission joining - Actions
- Implement rocket booking cancellation - Actions
- Implement mission leaving - Actions
- Switch badges for Missions - Conditional components
- Switch badges for Rockets - Conditional components
- Display reserved rockets in My profile - Filters
- Display joined missions in My profile - Filters

2021-11-25 01:47 UTC, Mihndim2020 requested changes
### Hi @mistermaxis & @ixboy, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file
:heavy_check_mark: The project is running as it should

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments below and under the review._

- [ ] As it is a requirement for this project and best practice, please kindly add tests to your project, this will ensure your app does break when you make changes. See screenshot of the project requirement below and kindly fix that. 

![team1](https://user-images.githubusercontent.com/65852621/143355179-f6786bde-d5cf-4e63-bd95-833c047015b6.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Directories for all Redux state slice files should be created (rockets, missions). It would be nice to implement that as it makes your code more organized.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 16:33 UTC, ArthurGC requested changes
# Required Changes ♻️ :warning: 
Hi  Team

Great work on making the changes requested by a previous reviewer. 👏 
You've done well implementing some of the requested changes but there are some issues that you still need to work on to go to the next project but you are almost there! 

![](https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Good Points :+1: :
Great job following the first reviewer's suggestions :heavy_check_mark:

## Aspects to improve ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-26 16:33 UTC, ArthurGC commented on src/components/missions/missions.test.js
> +    const badges = await screen.findAllByText('NOT A MEMBER');
- [ ] Please, It would be better if you fix your test because there are failing. ♻️ 

![test-space](https://user-images.githubusercontent.com/79876959/143609919-6a58384f-7914-4222-b174-37acdc0056bc.PNG)

2021-11-26 19:00 UTC, AshakaE requested changes
### Hi Team 🙋 , 

Please work on the changes requested by a previous reviewer 👏 
The tests are still failing 
<img src="https://media.giphy.com/media/suz7EO1YweWfC/giphy.gif"/>

 # Required Changes ♻️ 🚧 
_Check the comments under the review._

### Optional Suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 19:21 UTC, mistermaxis commented
![test](https://user-images.githubusercontent.com/87093942/143623125-319c5a94-21d8-4651-8b53-8188178d9fb1.png)

> I'm sorry but they are working on my machine.

2021-11-26 19:36 UTC, dasileker approved these changes
## **Hi @mistermaxis,** 

### **Awesome Work Team 👏👌**

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 
![Approved](https://user-images.githubusercontent.com/61562626/143624130-f38d74ab-74ca-4f35-916b-e56aa205ca19.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 02:16 UTC, merged